theme: minima
title: Projects and shit
author: mizuhame
email: mizuhame@tutanota.com
description: > # this means to ignore newlines until "baseurl:"
  we shit we fart.
  do you shit?
  do you fart?

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
